/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gplay.downloader

import kotlin.test.Test
import kotlin.test.assertEquals
import java.io.File

class AppTest {
    @Test fun canReadAuthConfig() {
        val email = "someone@gmail.com"
        val aasToken = "some_random_token"
        val file = File("authconfig.txt")
        file.writeText("$email $aasToken")

        val log = Logger(saveToFile = false, printToScreen = true, coloredOutput = true)
        val config = ConfigManager(log, "authconfig.txt").getNextConfig().authConfig
        assertEquals(config.email, email)
        assertEquals(config.aasToken, aasToken)
        file.delete()
    }

    @Test fun canReadAppIds() {
        val appIds = listOf(
            "com.github.android",
            "com.whatsapp",
            "somerandromappid",
        )

        val file = File("appids_test.txt")
        val txt = appIds.joinToString(separator="\n")
        file.writeText(txt)

        val result = readAppIds(file.path)
        assertEquals(result.size, appIds.size)

        for ((index, item) in result.withIndex()) {
            assertEquals(item, appIds[index])
        }
        file.delete()
    }
}
